import { JSX } from "react"

export function getWeatherCode(icon: string): string | JSX.Element {
  const weatherMap: { [key: string]: string | JSX.Element } = {
    snow: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="gradient1"
            x1="22.56"
            x2="39.2"
            y1="21.96"
            y2="50.8"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#f3f7fe"
            />
            <stop
              offset="0.45"
              stopColor="#f3f7fe"
            />
            <stop
              offset="1"
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="gradient2"
            x1="30.12"
            x2="31.88"
            y1="43.48"
            y2="46.52"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#86c3db"
            />
            <stop
              offset="0.45"
              stopColor="#86c3db"
            />
            <stop
              offset="1"
              stopColor="#5eafcf"
            />
          </linearGradient>
          <linearGradient
            id="gradient3"
            x1="29.67"
            x2="32.33"
            y1="42.69"
            y2="47.31"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient4"
            x1="23.12"
            x2="24.88"
            y1="43.48"
            y2="46.52"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient5"
            x1="22.67"
            x2="25.33"
            y1="42.69"
            y2="47.31"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient6"
            x1="37.12"
            x2="38.88"
            y1="43.48"
            y2="46.52"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient7"
            x1="36.67"
            x2="39.33"
            y1="42.69"
            y2="47.31"
            xlinkHref="#gradient2"
          />
        </defs>
        <path
          fill="url(#gradient1)"
          stroke="#e6effc"
          strokeMiterlimit="10"
          strokeWidth="0.5"
          d="M46.5 31.5h-.32a10.49 10.49 0 00-19.11-8 7 7 0 00-10.57 6 7.21 7.21 0 00.1 1.14A7.5 7.5 0 0018 45.5a4.19 4.19 0 00.5 0v0h28a7 7 0 000-14z"
        />
        <g>
          <circle
            cx="31"
            cy="45"
            r="1.25"
            fill="none"
            stroke="url(#gradient2)"
            strokeMiterlimit="10"
          />
          <path
            fill="none"
            stroke="url(#gradient3)"
            strokeLinecap="round"
            strokeMiterlimit="10"
            d="M33.17 46.25l-1.09-.63m-2.16-1.24l-1.09-.63M31 42.5v1.25m0 3.75v-1.25m-1.08-.63l-1.09.63m4.34-2.5l-1.09.63"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="4s"
            repeatCount="indefinite"
            type="translate"
            values="-1 -6; 1 12"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="9s"
            repeatCount="indefinite"
            type="rotate"
            values="0 31 45; 360 31 45"
          />
          <animate
            attributeName="opacity"
            dur="4s"
            repeatCount="indefinite"
            values="0;1;1;1;0"
          />
        </g>
        <g>
          <circle
            cx="24"
            cy="45"
            r="1.25"
            fill="none"
            stroke="url(#gradient4)"
            strokeMiterlimit="10"
          />
          <path
            fill="none"
            stroke="url(#gradient5)"
            strokeLinecap="round"
            strokeMiterlimit="10"
            d="M26.17 46.25l-1.09-.63m-2.16-1.24l-1.09-.63M24 42.5v1.25m0 3.75v-1.25m-1.08-.63l-1.09.63m4.34-2.5l-1.09.63"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            begin="-2s"
            dur="4s"
            repeatCount="indefinite"
            type="translate"
            values="1 -6; -1 12"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="9s"
            repeatCount="indefinite"
            type="rotate"
            values="0 24 45; 360 24 45"
          />
          <animate
            attributeName="opacity"
            begin="-2s"
            dur="4s"
            repeatCount="indefinite"
            values="0;1;1;1;0"
          />
        </g>
        <g>
          <circle
            cx="38"
            cy="45"
            r="1.25"
            fill="none"
            stroke="url(#gradient6)"
            strokeMiterlimit="10"
          />
          <path
            fill="none"
            stroke="url(#gradient7)"
            strokeLinecap="round"
            strokeMiterlimit="10"
            d="M40.17 46.25l-1.09-.63m-2.16-1.24l-1.09-.63M38 42.5v1.25m0 3.75v-1.25m-1.08-.63l-1.09.63m4.34-2.5l-1.09.63"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            begin="-1s"
            dur="4s"
            repeatCount="indefinite"
            type="translate"
            values="1 -6; -1 12"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="9s"
            repeatCount="indefinite"
            type="rotate"
            values="0 38 45; 360 38 45"
          />
          <animate
            attributeName="opacity"
            begin="-1s"
            dur="4s"
            repeatCount="indefinite"
            values="0;1;1;1;0"
          />
        </g>
      </svg>
    ),
    "snow-showers-day": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="gradient1"
            x1="22.56"
            x2="39.2"
            y1="21.96"
            y2="50.8"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#f3f7fe"
            />
            <stop
              offset="0.45"
              stopColor="#f3f7fe"
            />
            <stop
              offset="1"
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="gradient2"
            x1="30.12"
            x2="31.88"
            y1="43.48"
            y2="46.52"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#86c3db"
            />
            <stop
              offset="0.45"
              stopColor="#86c3db"
            />
            <stop
              offset="1"
              stopColor="#5eafcf"
            />
          </linearGradient>
          <linearGradient
            id="gradient3"
            x1="29.67"
            x2="32.33"
            y1="42.69"
            y2="47.31"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient4"
            x1="23.12"
            x2="24.88"
            y1="43.48"
            y2="46.52"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient5"
            x1="22.67"
            x2="25.33"
            y1="42.69"
            y2="47.31"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient6"
            x1="37.12"
            x2="38.88"
            y1="43.48"
            y2="46.52"
            xlinkHref="#gradient2"
          />
          <linearGradient
            id="gradient7"
            x1="36.67"
            x2="39.33"
            y1="42.69"
            y2="47.31"
            xlinkHref="#gradient2"
          />
        </defs>
        <path
          fill="url(#gradient1)"
          stroke="#e6effc"
          strokeMiterlimit="10"
          strokeWidth="0.5"
          d="M46.5 31.5h-.32a10.49 10.49 0 00-19.11-8 7 7 0 00-10.57 6 7.21 7.21 0 00.1 1.14A7.5 7.5 0 0018 45.5a4.19 4.19 0 00.5 0v0h28a7 7 0 000-14z"
        />
        <g>
          <circle
            cx="31"
            cy="45"
            r="1.25"
            fill="none"
            stroke="url(#gradient2)"
            strokeMiterlimit="10"
          />
          <path
            fill="none"
            stroke="url(#gradient3)"
            strokeLinecap="round"
            strokeMiterlimit="10"
            d="M33.17 46.25l-1.09-.63m-2.16-1.24l-1.09-.63M31 42.5v1.25m0 3.75v-1.25m-1.08-.63l-1.09.63m4.34-2.5l-1.09.63"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="4s"
            repeatCount="indefinite"
            type="translate"
            values="-1 -6; 1 12"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="9s"
            repeatCount="indefinite"
            type="rotate"
            values="0 31 45; 360 31 45"
          />
          <animate
            attributeName="opacity"
            dur="4s"
            repeatCount="indefinite"
            values="0;1;1;1;0"
          />
        </g>
        <g>
          <circle
            cx="24"
            cy="45"
            r="1.25"
            fill="none"
            stroke="url(#gradient4)"
            strokeMiterlimit="10"
          />
          <path
            fill="none"
            stroke="url(#gradient5)"
            strokeLinecap="round"
            strokeMiterlimit="10"
            d="M26.17 46.25l-1.09-.63m-2.16-1.24l-1.09-.63M24 42.5v1.25m0 3.75v-1.25m-1.08-.63l-1.09.63m4.34-2.5l-1.09.63"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            begin="-2s"
            dur="4s"
            repeatCount="indefinite"
            type="translate"
            values="1 -6; -1 12"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="9s"
            repeatCount="indefinite"
            type="rotate"
            values="0 24 45; 360 24 45"
          />
          <animate
            attributeName="opacity"
            begin="-2s"
            dur="4s"
            repeatCount="indefinite"
            values="0;1;1;1;0"
          />
        </g>
        <g>
          <circle
            cx="38"
            cy="45"
            r="1.25"
            fill="none"
            stroke="url(#gradient6)"
            strokeMiterlimit="10"
          />
          <path
            fill="none"
            stroke="url(#gradient7)"
            strokeLinecap="round"
            strokeMiterlimit="10"
            d="M40.17 46.25l-1.09-.63m-2.16-1.24l-1.09-.63M38 42.5v1.25m0 3.75v-1.25m-1.08-.63l-1.09.63m4.34-2.5l-1.09.63"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            begin="-1s"
            dur="4s"
            repeatCount="indefinite"
            type="translate"
            values="1 -6; -1 12"
          />
          <animateTransform
            additive="sum"
            attributeName="transform"
            dur="9s"
            repeatCount="indefinite"
            type="rotate"
            values="0 38 45; 360 38 45"
          />
          <animate
            attributeName="opacity"
            begin="-1s"
            dur="4s"
            repeatCount="indefinite"
            values="0;1;1;1;0"
          />
        </g>
      </svg>
    ),
    "snow-showers-night": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="grad_b_zt89"
            x1="16.5"
            x2="21.5"
            y1="19.67"
            y2="28.33"
          >
            <stop
              offset="0"
              stopColor="#fbbf24"
            />
            <stop
              offset="0.45"
              stopColor="#fbbf24"
            />
            <stop
              offset="1"
              stopColor="#f59e0b"
            />
          </linearGradient>
          <linearGradient
            id="grad_c_xr72"
            x1="22.56"
            x2="39.2"
            y1="21.96"
            y2="50.8"
          >
            <stop
              offset="0"
              stopColor="#f3f7fe"
            />
            <stop
              offset="0.45"
              stopColor="#f3f7fe"
            />
            <stop
              offset="1"
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="grad_a_qp61"
            x1="22.53"
            x2="25.47"
            y1="42.95"
            y2="48.05"
          >
            <stop
              offset="0"
              stopColor="#4286ee"
            />
            <stop
              offset="0.45"
              stopColor="#4286ee"
            />
            <stop
              offset="1"
              stopColor="#0950bc"
            />
          </linearGradient>
          <linearGradient
            id="grad_d_wx54"
            x1="29.53"
            x2="32.47"
            y1="42.95"
            y2="48.05"
            xlinkHref="#grad_a_qp61"
          />
          <linearGradient
            id="grad_e_lt32"
            x1="36.53"
            x2="39.47"
            y1="42.95"
            y2="48.05"
            xlinkHref="#grad_a_qp61"
          />
          <linearGradient
            id="grad_f_pl90"
            x1="26.74"
            x2="35.76"
            y1="37.88"
            y2="53.52"
          >
            <stop
              offset="0"
              stopColor="#f7b23b"
            />
            <stop
              offset="0.45"
              stopColor="#f7b23b"
            />
            <stop
              offset="1"
              stopColor="#f59e0b"
            />
          </linearGradient>
        </defs>
        <circle
          cx="19"
          cy="24"
          r="5"
          fill="url(#grad_b_zt89)"
          stroke="#f8af18"
          strokeMiterlimit="10"
          strokeWidth=".5"
        />
        <path
          fill="none"
          stroke="#fbbf24"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M19 15.67V12.5m0 23v-3.17m5.89-14.22l2.24-2.24M10.87 32.13l2.24-2.24m0-11.78l-2.24-2.24m16.26 16.26l-2.24-2.24M7.5 24h3.17m19.83 0h-3.17"
        >
          <animateTransform
            attributeName="transform"
            dur="45s"
            repeatCount="indefinite"
            type="rotate"
            values="0 19 24; 360 19 24"
          />
        </path>
        <path
          fill="url(#grad_c_xr72)"
          stroke="#e6effc"
          strokeMiterlimit="10"
          strokeWidth=".5"
          d="M46.5 31.5h-.32a10.49 10.49 0 00-19.11-8 7 7 0 00-10.57 6 7.21 7.21 0 00.1 1.14A7.5 7.5 0 0018 45.5a4.19 4.19 0 00.5 0v0h28a7 7 0 000-14z"
        />
        <path
          fill="none"
          stroke="url(#grad_a_qp61)"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M24.39 43.03l-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_d_wx54)"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M31.39 43.03l-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_e_lt32)"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M38.39 43.03l-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="url(#grad_f_pl90)"
          stroke="#f6a823"
          strokeMiterlimit="10"
          strokeWidth=".5"
          d="M30 36l-4 12h4l-2 10 10-14h-6l4-8h-6z"
        >
          <animate
            attributeName="opacity"
            dur="2s"
            repeatCount="indefinite"
            values="1; 1; 1; 1; 1; 1; 0.1; 1; 0.1; 1; 1; 0.1; 1; 0.1; 1"
          />
        </path>
      </svg>
    ),
    "thunder-rain": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="grad_b_zt89"
            x1="16.5"
            x2="21.5"
            y1="19.67"
            y2="28.33"
          >
            <stop
              offset="0"
              stopColor="#fbbf24"
            />
            <stop
              offset="0.45"
              stopColor="#fbbf24"
            />
            <stop
              offset="1"
              stopColor="#f59e0b"
            />
          </linearGradient>
          <linearGradient
            id="grad_c_xr72"
            x1="22.56"
            x2="39.2"
            y1="21.96"
            y2="50.8"
          >
            <stop
              offset="0"
              stopColor="#f3f7fe"
            />
            <stop
              offset="0.45"
              stopColor="#f3f7fe"
            />
            <stop
              offset="1"
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="grad_a_qp61"
            x1="22.53"
            x2="25.47"
            y1="42.95"
            y2="48.05"
          >
            <stop
              offset="0"
              stopColor="#4286ee"
            />
            <stop
              offset="0.45"
              stopColor="#4286ee"
            />
            <stop
              offset="1"
              stopColor="#0950bc"
            />
          </linearGradient>
          <linearGradient
            id="grad_d_wx54"
            x1="29.53"
            x2="32.47"
            y1="42.95"
            y2="48.05"
            xlinkHref="#grad_a_qp61"
          />
          <linearGradient
            id="grad_e_lt32"
            x1="36.53"
            x2="39.47"
            y1="42.95"
            y2="48.05"
            xlinkHref="#grad_a_qp61"
          />
          <linearGradient
            id="grad_f_pl90"
            x1="26.74"
            x2="35.76"
            y1="37.88"
            y2="53.52"
          >
            <stop
              offset="0"
              stopColor="#f7b23b"
            />
            <stop
              offset="0.45"
              stopColor="#f7b23b"
            />
            <stop
              offset="1"
              stopColor="#f59e0b"
            />
          </linearGradient>
        </defs>
        <circle
          cx="19"
          cy="24"
          r="5"
          fill="url(#grad_b_zt89)"
          stroke="#f8af18"
          strokeMiterlimit="10"
          strokeWidth=".5"
        />
        <path
          fill="none"
          stroke="#fbbf24"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M19 15.67V12.5m0 23v-3.17m5.89-14.22l2.24-2.24M10.87 32.13l2.24-2.24m0-11.78l-2.24-2.24m16.26 16.26l-2.24-2.24M7.5 24h3.17m19.83 0h-3.17"
        >
          <animateTransform
            attributeName="transform"
            dur="45s"
            repeatCount="indefinite"
            type="rotate"
            values="0 19 24; 360 19 24"
          />
        </path>
        <path
          fill="url(#grad_c_xr72)"
          stroke="#e6effc"
          strokeMiterlimit="10"
          strokeWidth=".5"
          d="M46.5 31.5h-.32a10.49 10.49 0 00-19.11-8 7 7 0 00-10.57 6 7.21 7.21 0 00.1 1.14A7.5 7.5 0 0018 45.5a4.19 4.19 0 00.5 0v0h28a7 7 0 000-14z"
        />
        <path
          fill="none"
          stroke="url(#grad_a_qp61)"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M24.39 43.03l-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_d_wx54)"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M31.39 43.03l-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_e_lt32)"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="2"
          d="M38.39 43.03l-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="url(#grad_f_pl90)"
          stroke="#f6a823"
          strokeMiterlimit="10"
          strokeWidth=".5"
          d="M30 36l-4 12h4l-2 10 10-14h-6l4-8h-6z"
        >
          <animate
            attributeName="opacity"
            dur="2s"
            repeatCount="indefinite"
            values="1; 1; 1; 1; 1; 1; 0.1; 1; 0.1; 1; 1; 0.1; 1; 0.1; 1"
          />
        </path>
      </svg>
    ),
    "thunder-showers-day": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="grad_a_yz92"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="grad_b_rx75"
            x1={26.74}
            x2={35.76}
            y1={37.88}
            y2={53.52}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f7b23b"
            />
            <stop
              offset={0.45}
              stopColor="#f7b23b"
            />
            <stop
              offset={1}
              stopColor="#f59e0b"
            />
          </linearGradient>
        </defs>
        <path
          fill="url(#grad_a_yz92)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
        <path
          fill="url(#grad_b_rx75)"
          stroke="#f6a823"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="m30 36-4 12h4l-2 10 10-14h-6l4-8h-6z"
        >
          <animate
            attributeName="opacity"
            dur="2s"
            repeatCount="indefinite"
            values="1; 1; 1; 1; 1; 1; 0.1; 1; 0.1; 1; 1; 0.1; 1; 0.1; 1"
          />
        </path>
      </svg>
    ),
    "thunder-showers-night": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="grad_a_yz92"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="grad_b_rx75"
            x1={26.74}
            x2={35.76}
            y1={37.88}
            y2={53.52}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f7b23b"
            />
            <stop
              offset={0.45}
              stopColor="#f7b23b"
            />
            <stop
              offset={1}
              stopColor="#f59e0b"
            />
          </linearGradient>
        </defs>
        <path
          fill="url(#grad_a_yz92)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
        <path
          fill="url(#grad_b_rx75)"
          stroke="#f6a823"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="m30 36-4 12h4l-2 10 10-14h-6l4-8h-6z"
        >
          <animate
            attributeName="opacity"
            dur="2s"
            repeatCount="indefinite"
            values="1; 1; 1; 1; 1; 1; 0.1; 1; 0.1; 1; 1; 0.1; 1; 0.1; 1"
          />
        </path>
      </svg>
    ),
    rain: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="grad_b_x71"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="grad_a_k29"
            x1={22.53}
            x2={25.47}
            y1={42.95}
            y2={48.05}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#4286ee"
            />
            <stop
              offset={0.45}
              stopColor="#4286ee"
            />
            <stop
              offset={1}
              stopColor="#0950bc"
            />
          </linearGradient>
          <linearGradient
            xlinkHref="#grad_a_k29"
            id="grad_c_w84"
            x1={29.53}
            x2={32.47}
            y1={42.95}
            y2={48.05}
          />
          <linearGradient
            xlinkHref="#grad_a_k29"
            id="grad_d_t53"
            x1={36.53}
            x2={39.47}
            y1={42.95}
            y2={48.05}
          />
        </defs>
        <path
          fill="url(#grad_b_x71)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
        <path
          fill="none"
          stroke="url(#grad_a_k29)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m24.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_c_w84)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m31.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_d_t53)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m38.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
      </svg>
    ),
    "showers-day": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="grad_b_x71"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="grad_a_k29"
            x1={22.53}
            x2={25.47}
            y1={42.95}
            y2={48.05}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#4286ee"
            />
            <stop
              offset={0.45}
              stopColor="#4286ee"
            />
            <stop
              offset={1}
              stopColor="#0950bc"
            />
          </linearGradient>
          <linearGradient
            xlinkHref="#grad_a_k29"
            id="grad_c_w84"
            x1={29.53}
            x2={32.47}
            y1={42.95}
            y2={48.05}
          />
          <linearGradient
            xlinkHref="#grad_a_k29"
            id="grad_d_t53"
            x1={36.53}
            x2={39.47}
            y1={42.95}
            y2={48.05}
          />
        </defs>
        <path
          fill="url(#grad_b_x71)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
        <path
          fill="none"
          stroke="url(#grad_a_k29)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m24.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_c_w84)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m31.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#grad_d_t53)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m38.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
      </svg>
    ),
    "showers-night": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="barra"
            x1={13.58}
            x2={24.15}
            y1={15.57}
            y2={33.87}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#86c3db"
            />
            <stop
              offset={0.45}
              stopColor="#86c3db"
            />
            <stop
              offset={1}
              stopColor="#5eafcf"
            />
            <animateTransform
              attributeName="gradientTransform"
              dur="10s"
              repeatCount="indefinite"
              type="rotate"
              values="10 19.22 24.293; -10 19.22 24.293; 10 19.22 24.293"
            />
          </linearGradient>
          <linearGradient
            id="capa"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
          <linearGradient
            id="ari"
            x1={22.53}
            x2={25.47}
            y1={42.95}
            y2={48.05}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#4286ee"
            />
            <stop
              offset={0.45}
              stopColor="#4286ee"
            />
            <stop
              offset={1}
              stopColor="#0950bc"
            />
          </linearGradient>
          <linearGradient
            xlinkHref="#ari"
            id="daz"
            x1={29.53}
            x2={32.47}
            y1={42.95}
            y2={48.05}
          />
          <linearGradient
            xlinkHref="#ari"
            id="epa"
            x1={36.53}
            x2={39.47}
            y1={42.95}
            y2={48.05}
          />
        </defs>
        <path
          fill="url(#barra)"
          stroke="#72b9d5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={0.5}
          d="M29.33 26.68a10.61 10.61 0 0 1-10.68-10.54A10.5 10.5 0 0 1 19 13.5a10.54 10.54 0 1 0 11.5 13.11 11.48 11.48 0 0 1-1.17.07z"
        >
          <animateTransform
            attributeName="transform"
            dur="10s"
            repeatCount="indefinite"
            type="rotate"
            values="-10 19.22 24.293; 10 19.22 24.293; -10 19.22 24.293"
          />
        </path>
        <path
          fill="url(#capa)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
        <path
          fill="none"
          stroke="url(#ari)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m24.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#d)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m31.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.4s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#epa)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="m38.39 43.03-.78 4.94"
        >
          <animateTransform
            attributeName="transform"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            type="translate"
            values="1 -5; -2 10"
          />
          <animate
            attributeName="opacity"
            begin="-0.2s"
            dur="0.7s"
            repeatCount="indefinite"
            values="0;1;1;0"
          />
        </path>
      </svg>
    ),
    fog: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="america"
            x1={27.5}
            x2={36.5}
            y1={17.21}
            y2={32.79}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#d4d7dd"
            />
            <stop
              offset={0.45}
              stopColor="#d4d7dd"
            />
            <stop
              offset={1}
              stopColor="#bec1c6"
            />
          </linearGradient>
          <linearGradient
            xlinkHref="#america"
            id="bacr"
            y1={24.21}
            y2={39.79}
          />
          <linearGradient
            xlinkHref="#america"
            id="cat"
            y1={31.21}
            y2={46.79}
          />
        </defs>
        <path
          fill="none"
          stroke="url(#america)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={3}
          d="M17 25h30"
        >
          <animateTransform
            attributeName="transform"
            begin="0s"
            dur="5s"
            repeatCount="indefinite"
            type="translate"
            values="-4 0; 4 0; -4 0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#bacr)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={3}
          d="M17 32h30"
        >
          <animateTransform
            attributeName="transform"
            begin="-2s"
            dur="5s"
            repeatCount="indefinite"
            type="translate"
            values="-3 0; 3 0; -3 0"
          />
        </path>
        <path
          fill="none"
          stroke="url(#cat)"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={3}
          d="M17 39h30"
        >
          <animateTransform
            attributeName="transform"
            begin="-4s"
            dur="5s"
            repeatCount="indefinite"
            type="translate"
            values="-4 0; 4 0; -4 0"
          />
        </path>
      </svg>
    ),
    wind: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="fido"
            x1={27.56}
            x2={38.27}
            y1={17.64}
            y2={36.19}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#d4d7dd"
            />
            <stop
              offset={0.45}
              stopColor="#d4d7dd"
            />
            <stop
              offset={1}
              stopColor="#bec1c6"
            />
          </linearGradient>
          <linearGradient
            xlinkHref="#fido"
            id="dido"
            x1={19.96}
            x2={31.37}
            y1={29.03}
            y2={48.8}
          />
        </defs>
        <path
          fill="none"
          stroke="url(#fido)"
          strokeDasharray="35 22"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={3}
          d="M43.64 20a5 5 0 1 1 3.61 8.46h-35.5"
        >
          <animate
            attributeName="stroke-dashoffset"
            dur="2s"
            repeatCount="indefinite"
            values="-57; 57"
          />
        </path>
        <path
          fill="none"
          stroke="url(#dido)"
          strokeDasharray="24 15"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={3}
          d="M29.14 44a5 5 0 1 0 3.61-8.46h-21"
        >
          <animate
            attributeName="stroke-dashoffset"
            begin="-1.5s"
            dur="2s"
            repeatCount="indefinite"
            values="-39; 39"
          />
        </path>
      </svg>
    ),
    cloudy: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="uniqueGradient"
            x1="22.56"
            x2="39.2"
            y1="21.96"
            y2="50.8"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#f3f7fe"
            />
            <stop
              offset="0.45"
              stopColor="#f3f7fe"
            />
            <stop
              offset="1"
              stopColor="#deeafb"
            />
          </linearGradient>
        </defs>
        <path
          fill="url(#uniqueGradient)"
          stroke="#e6effc"
          strokeMiterlimit="10"
          strokeWidth="0.5"
          d="M46.5 31.5h-.32a10.49 10.49 0 00-19.11-8 7 7 0 00-10.57 6 7.21 7.21 0 00.1 1.14A7.5 7.5 0 0018 45.5a4.19 4.19 0 00.5 0v0h28a7 7 0 000-14z"
        >
          <animateTransform
            attributeName="transform"
            dur="7s"
            repeatCount="indefinite"
            type="translate"
            values="-3 0; 3 0; -3 0"
          />
        </path>
      </svg>
    ),
    "partly-cloudy-day": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="amigo"
            x1={16.5}
            x2={21.5}
            y1={19.67}
            y2={28.33}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#fbbf24"
            />
            <stop
              offset={0.45}
              stopColor="#fbbf24"
            />
            <stop
              offset={1}
              stopColor="#f59e0b"
            />
          </linearGradient>
          <linearGradient
            id="baz"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
        </defs>
        <circle
          cx={19}
          cy={24}
          r={5}
          fill="url(#amigo)"
          stroke="#f8af18"
          strokeMiterlimit={10}
          strokeWidth={0.5}
        />
        <path
          fill="none"
          stroke="#fbbf24"
          strokeLinecap="round"
          strokeMiterlimit={10}
          strokeWidth={2}
          d="M19 15.67V12.5m0 23v-3.17m5.89-14.22 2.24-2.24M10.87 32.13l2.24-2.24m0-11.78-2.24-2.24m16.26 16.26-2.24-2.24M7.5 24h3.17m19.83 0h-3.17"
        >
          <animateTransform
            attributeName="transform"
            dur="45s"
            repeatCount="indefinite"
            type="rotate"
            values="0 19 24; 360 19 24"
          />
        </path>
        <path
          fill="url(#baz)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
      </svg>
    ),
    "partly-cloudy-night": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="qw"
            x1={13.58}
            x2={24.15}
            y1={15.57}
            y2={33.87}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#86c3db"
            />
            <stop
              offset={0.45}
              stopColor="#86c3db"
            />
            <stop
              offset={1}
              stopColor="#5eafcf"
            />
            <animateTransform
              attributeName="gradientTransform"
              dur="10s"
              repeatCount="indefinite"
              type="rotate"
              values="10 19.22 24.293; -10 19.22 24.293; 10 19.22 24.293"
            />
          </linearGradient>
          <linearGradient
            id="zq"
            x1={22.56}
            x2={39.2}
            y1={21.96}
            y2={50.8}
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset={0}
              stopColor="#f3f7fe"
            />
            <stop
              offset={0.45}
              stopColor="#f3f7fe"
            />
            <stop
              offset={1}
              stopColor="#deeafb"
            />
          </linearGradient>
        </defs>
        <path
          fill="url(#qw)"
          stroke="#72b9d5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={0.5}
          d="M29.33 26.68a10.61 10.61 0 0 1-10.68-10.54A10.5 10.5 0 0 1 19 13.5a10.54 10.54 0 1 0 11.5 13.11 11.48 11.48 0 0 1-1.17.07z"
        >
          <animateTransform
            attributeName="transform"
            dur="10s"
            repeatCount="indefinite"
            type="rotate"
            values="-10 19.22 24.293; 10 19.22 24.293; -10 19.22 24.293"
          />
        </path>
        <path
          fill="url(#zq)"
          stroke="#e6effc"
          strokeMiterlimit={10}
          strokeWidth={0.5}
          d="M46.5 31.5h-.32a10.49 10.49 0 0 0-19.11-8 7 7 0 0 0-10.57 6 7.21 7.21 0 0 0 .1 1.14A7.5 7.5 0 0 0 18 45.5a4.19 4.19 0 0 0 .5 0h28a7 7 0 0 0 0-14z"
        />
      </svg>
    ),
    "clear-day": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="wido"
            x1="26.75"
            x2="37.25"
            y1="22.91"
            y2="41.09"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#fbbf24"
            />
            <stop
              offset=".45"
              stopColor="#fbbf24"
            />
            <stop
              offset="1"
              stopColor="#f59e0b"
            />
          </linearGradient>
        </defs>
        <circle
          cx="32"
          cy="32"
          r="10.5"
          fill="url(#wido)"
          stroke="#f8af18"
          strokeMiterlimit="10"
          strokeWidth=".5"
        />
        <path
          fill="none"
          stroke="#fbbf24"
          strokeLinecap="round"
          strokeMiterlimit="10"
          strokeWidth="3"
          d="M32 15.71V9.5m0 45v-6.21m11.52-27.81l4.39-4.39M16.09 47.91l4.39-4.39m0-23l-4.39-4.39m31.82 31.78l-4.39-4.39M15.71 32H9.5m45 0h-6.21"
        >
          <animateTransform
            attributeName="transform"
            dur="45s"
            repeatCount="indefinite"
            type="rotate"
            values="0 32 32; 360 32 32"
          />
        </path>
      </svg>
    ),
    "clear-night": (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 64 64"
        className="h-9 w-9"
      >
        <defs>
          <linearGradient
            id="z"
            x1="21.92"
            x2="38.52"
            y1="18.75"
            y2="47.52"
            gradientUnits="userSpaceOnUse"
          >
            <stop
              offset="0"
              stopColor="#86c3db"
            />
            <stop
              offset=".45"
              stopColor="#86c3db"
            />
            <stop
              offset="1"
              stopColor="#5eafcf"
            />
            <animateTransform
              attributeName="gradientTransform"
              dur="10s"
              repeatCount="indefinite"
              type="rotate"
              values="5 32 32; -15 32 32; 5 32 32"
            />
          </linearGradient>
        </defs>
        <path
          fill="url(#z)"
          stroke="#72b9d5"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth=".5"
          d="M46.66 36.2a16.66 16.66 0 01-16.78-16.55 16.29 16.29 0 01.55-4.15A16.56 16.56 0 1048.5 36.1c-.61.06-1.22.1-1.84.1z"
        >
          <animateTransform
            attributeName="transform"
            dur="10s"
            repeatCount="indefinite"
            type="rotate"
            values="-5 32 32; 15 32 32; -5 32 32"
          />
        </path>
      </svg>
    ),
  }

  return weatherMap[icon]
}
